import { ThemeProvider, createTheme } from "@mui/material/styles";
import Head from "next/head";
import { Toaster } from "react-hot-toast";
import "../styles/globals.css";
import Navbar from "../views/Navbar";
import { Box } from "@mui/material";

export default function App({ Component, pageProps }) {
  const theme = createTheme();

  return (
    <>
      <Head>
        <title>SJF Simulator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <Box
          sx={{
            minHeight: "100vh",
            backgroundColor: (theme) => theme.palette.grey[100],
          }}
        >
          <Navbar />
          <Box
            sx={{
              p: 5,
              pt: 10,
            }}
          >
            <Component {...pageProps} />
          </Box>
        </Box>
      </ThemeProvider>
      <Toaster
        position="top-right"
        toastOptions={{
          duration: 3000,
        }}
      />
    </>
  );
}
